<?php

class Phuong_Blog_Block_Adminhtml_User_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        parent::__construct();

        $this->setId('user_grid');
        $this->setDefaultSort('user_id');
        $this->setDefaultDir('DESC');
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getModel('blog/users')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection();
    }

    protected function _prepareColumns()
    {
        $this->addColumn('user_id', array(
            'index'    => 'user_id',
            'header'   => Mage::helper('blog')->__('User id'),
            'type'     => 'number',
            'sortable' => true,
            'width'    => '100px'
            ));

        $this->addColumn('username', array(
            'index'    => 'username',
            'header'   => Mage::helper('blog')->__('Username'),
            'sortable' => false
        ));

        $this->addColumn('email', array(
            'index'    => 'email',
            'header'   => Mage::helper('blog')->__('Email'),
            'sortable' => false
        ));

        $this->addColumn('status', array(
            'index'    => 'status',
            'header'   => Mage::helper('blog')->__('Status'),
            'sortable' => false
        ));
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    public function getGridUrl()
    {
        return $this->getUrl('*/*/grid', array('_current' => true));
    }
}