<?php

class Foggyline_Logger_Model_Log_Writer_Stream extends Zend_Log_Writer_Stream
{
    private static $_flfp;

    public function __construct($streamOrUrl, $mode = null) {
        self::$_flfp = $streamOrUrl;
        parent::__construct($streamOrUrl, $mode);
    }

    protected function _write($event) {
        $logger = Mage::getModel('foggyline_logger/logger');

        $logger->setTimestamp($event['timestamp']);
        $logger->setMessage($event['message']);
        $logger->setPriority($event['priority']);
        $logger->setPriorityName($event['priorityName']);
        if (is_string(self::$_flfp)) {
            $logger->setFile(self::$_flfp);
        }
        try {
            $logger->save();
        } catch (Exception $e) {

        }

        parent::_write($event); // TODO: Change the autogenerated stub
    }
}